name: dolphin_read
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  flare_flutter: ^2.0.5
  smart_flare: any
  # 屏幕适配 
  flutter_screenutil: ^2.1.0
  # 本地缓存
  shared_preferences: ^0.5.8
  # 网络请求
  dio: ^3.0.9
  # 请求缓存
  dio_http_cache: ^0.2.8
  # 轻提示
  bot_toast: ^3.0.1
  # 路由
  fluro: ^1.6.3
  # 底部导航
  convex_bottom_bar: ^2.4.0
  # 下拉刷新
  flutter_easyrefresh: ^2.1.5
  # 轮播
  flutter_swiper: ^1.1.6
  # 骨架屏
  shimmer: ^1.1.1
  # 短信
  mobsms: ^1.1.0
  # 搜索框
  floating_search_bar: ^0.3.0
  # 带缓存的图片
  cached_network_image: ^2.2.0+1
  # 加载动图
  flutter_spinkit: "^4.1.2"
  # 抽屉
  flutter_inner_drawer: "^0.5.7+2"
  # HTML加载
  flutter_html: "^1.0.2"
  # 弹窗
  awesome_dialog: "^1.1.3"
  # 左右滑动
  flutter_slidable: "^0.5.5"
  # 状态管理
  provider: ^4.3.2
  
dev_dependencies:

  

  flutter_test:
    sdk: flutter

    

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
      - assets/Teddy.flr
      - assets/button-animation.flr
      - assets/images/no-data.png
      - assets/images/loading.png


  
  fonts:
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/iconfont.ttf


